architecture:
  out_dim: 2
  in_channels: 1
  pooling: mean
training:
  batch_size: 32
  epochs: 20
  lr: 0.01
  optimizer: AdamW
  scheduler: None
  criterion: LabelSmoothingCrossEntropyLoss
  label_smoothing: 0.3
  weight_decay: 0.1
  dropout: 0.2
  clip_grad_norm: 1.0
  ema: true
  ema_decay: 0.999
data:
  from_eeg_data: true
  from_synth_dis: true
  from_synth_sd: true
  dis_data_dir: /data/shared/signal-diffusion/generated_images_dis-split/
  sd_data_dir: /data/shared/signal-diffusion/generated_images_sd-split/
  transform: trivial_augment_wide
